### ISSUE TITLE
Анализ диапазона

### ISSUE THREAD

**Issue by willstay** [Khorcus/liga-internship#3]
Среди методов не увидел анализ диапазона. Несколько раз просмотрел код, но может пропустил.

**Comment by Khorcus** [comment]
Методы highestNote() и lowestNote() предоставляют весь функционал для анализа диапазона. Они используются в ReportBuilder, чтобы вычислить этот самый диапазон и составить отчет. Думаю, да, не нужно вносить лишнюю логику в ReportBuilder. Исправил.
